
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package microjs.jcompiler.frontend.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int MOD = 28;
  public static final int ELSE = 12;
  public static final int PLUS = 16;
  public static final int INT = 31;
  public static final int RPAREN = 6;
  public static final int WHILE = 29;
  public static final int RCURLY = 8;
  public static final int IDENTIFIER = 30;
  public static final int RETURN = 24;
  public static final int FUNCTION = 14;
  public static final int IF = 11;
  public static final int LPAREN = 5;
  public static final int LBRACKET = 9;
  public static final int RBRACKET = 10;
  public static final int LCURLY = 7;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int TIMESASSIGN = 22;
  public static final int PLUSASSIGN = 20;
  public static final int DIV = 19;
  public static final int SEMICOL = 2;
  public static final int MINUS = 17;
  public static final int error = 1;
  public static final int LET = 4;
  public static final int EQ = 25;
  public static final int MINUSASSIGN = 21;
  public static final int BOOL = 32;
  public static final int EQEQ = 26;
  public static final int DIVASSIGN = 23;
  public static final int VAR = 3;
  public static final int UMINUS = 27;
  public static final int LAMBDA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOL",
  "VAR",
  "LET",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "LBRACKET",
  "RBRACKET",
  "IF",
  "ELSE",
  "COMMA",
  "FUNCTION",
  "LAMBDA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "PLUSASSIGN",
  "MINUSASSIGN",
  "TIMESASSIGN",
  "DIVASSIGN",
  "RETURN",
  "EQ",
  "EQEQ",
  "UMINUS",
  "MOD",
  "WHILE",
  "IDENTIFIER",
  "INT",
  "BOOL"
  };
}

